const mongoose = require("mongoose");
const db = require("../models");

mongoose.connect(
  process.env.MONGODB_URI || "mongodb://localhost/reactsuperhero"
);

const villainSeed = [
  {
    name: "Lex Luthor",
    hero_id: 405,
    intel: 100,
    strength: 53,
    speed: 25,
    durability: 65,
    power: 68,
    combat: 70,
    total_power: 381,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/727.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Doctor Doom",
    hero_id: 222,
    intel: 100,
    strength: 32,
    speed: 20,
    durability: 100,
    power: 100,
    combat: 84,
    total_power: 436,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/189.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Mister Freeze",
    hero_id: 457,
    intel: 75,
    strength: 32,
    speed: 12,
    durability: 70,
    power: 37,
    combat: 28,
    total_power: 254,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/742.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "juggernaut",
    hero_id: 374,
    intel: 44,
    strength: 100,
    speed: 42,
    durability: 100,
    power: 85,
    combat: 70,
    total_power: 441,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/826.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Abomination",
    hero_id: 4,
    intel: 63,
    strength: 80,
    speed: 53,
    durability: 90,
    power: 62,
    combat: 95,
    total_power: 443,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Doomsday",
    hero_id: 230,
    intel: 75,
    strength: 100,
    speed: 67,
    durability: 100,
    power: 100,
    combat: 90,
    total_power: 532,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/679.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Professor Zoom",
    hero_id: 528,
    intel: 94,
    strength: 10,
    speed: 100,
    durability: 20,
    power: 83,
    combat: 20,
    total_power: 317,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/766.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Carnage",
    hero_id: 162,
    intel: 63,
    strength: 63,
    speed: 70,
    durability: 84,
    power: 88,
    combat: 90,
    total_power: 458,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/187.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "General Zod",
    hero_id: 278,
    intel: 94,
    strength: 100,
    speed: 96,
    durability: 100,
    power: 100,
    combat: 95,
    total_power: 585,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/837.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Thanos",
    hero_id: 655,
    intel: 100,
    strength: 100,
    speed: 33,
    durability: 100,
    power: 100,
    combat: 80,
    total_power: 513,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1305.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Magneto",
    hero_id: 423,
    intel: 88,
    strength: 80,
    speed: 27,
    durability: 84,
    power: 91,
    combat: 80,
    total_power: 450,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/12.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Darkseid",
    hero_id: 204,
    intel: 88,
    strength: 100,
    speed: 83,
    durability: 100,
    power: 100,
    combat: 95,
    total_power: 566,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/668.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Loki",
    hero_id: 414,
    intel: 88,
    strength: 63,
    speed: 46,
    durability: 85,
    power: 100,
    combat: 60,
    total_power: 442,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/928.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Kingpin",
    hero_id: 391,
    intel: 75,
    strength: 18,
    speed: 25,
    durability: 40,
    power: 13,
    combat: 70,
    total_power: 241,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/623.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Green Goblin",
    hero_id: 299,
    intel: 100,
    strength: 48,
    speed: 38,
    durability: 60,
    power: 48,
    combat: 50,
    total_power: 344,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/25.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Red Skull",
    hero_id: 550,
    intel: 75,
    strength: 10,
    speed: 12,
    durability: 14,
    power: 19,
    combat: 80,
    total_power: 210,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1392.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Black Adam",
    hero_id: 95,
    intel: 88,
    strength: 100,
    speed: 92,
    durability: 100,
    power: 100,
    combat: 56,
    total_power: 536,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/643.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Brainiac",
    hero_id: 136,
    intel: 100,
    strength: 95,
    speed: 63,
    durability: 90,
    power: 60,
    combat: 75,
    total_power: 483,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/648.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Venom",
    hero_id: 687,
    intel: 75,
    strength: 57,
    speed: 65,
    durability: 84,
    power: 86,
    combat: 84,
    total_power: 451,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/22.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Ultron",
    hero_id: 680,
    intel: 88,
    strength: 83,
    speed: 42,
    durability: 100,
    power: 100,
    combat: 64,
    total_power: 457,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1339.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Apocalypse",
    hero_id: 35,
    intel: 100,
    strength: 100,
    speed: 33,
    durability: 100,
    power: 100,
    combat: 60,
    total_power: 493,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/852.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Doctor Octopus",
    hero_id: 225,
    intel: 94,
    strength: 48,
    speed: 33,
    durability: 40,
    power: 53,
    combat: 65,
    total_power: 333,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/622.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Sabretooth",
    hero_id: 570,
    intel: 56,
    strength: 48,
    speed: 38,
    durability: 90,
    power: 50,
    combat: 100,
    total_power: 382,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/17.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Harley Quinn",
    hero_id: 309,
    intel: 88,
    strength: 12,
    speed: 33,
    durability: 65,
    power: 55,
    combat: 80,
    total_power: 333,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/701.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Riddler",
    hero_id: 558,
    intel: 100,
    strength: 10,
    speed: 12,
    durability: 14,
    power: 10,
    combat: 14,
    total_power: 160,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/768.jpg",
    date: new Date(Date.now()),
  },

  {
    name: "Mysterio",
    hero_id: 479,
    intel: 81,
    strength: 10,
    speed: 17,
    durability: 40,
    power: 82,
    combat: 70,
    total_power: 300,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1039.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Galactus",
    hero_id: 273,
    intel: 100,
    strength: 100,
    speed: 83,
    durability: 100,
    power: 100,
    combat: 50,
    total_power: 533,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/862.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Ras Al Ghul",
    hero_id: 538,
    intel: 100,
    strength: 28,
    speed: 32,
    durability: 42,
    power: 27,
    combat: 100,
    total_power: 329,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/761.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Ozymandias",
    hero_id: 508,
    intel: 100,
    strength: 18,
    speed: 33,
    durability: 20,
    power: 49,
    combat: 95,
    total_power: 315,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1063.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Bizarro",
    hero_id: 93,
    intel: 38,
    strength: 95,
    speed: 100,
    durability: 100,
    power: 100,
    combat: 85,
    total_power: 518,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/642.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Evil Chuck Norris",
    hero_id: 176,
    intel: 50,
    strength: 80,
    speed: 47,
    durability: 56,
    power: 42,
    combat: 99,
    total_power: 374,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/954.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Evil Deadpool",
    hero_id: 247,
    intel: 69,
    strength: 32,
    speed: 50,
    durability: 100,
    power: 100,
    combat: 100,
    total_power: 451,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/10090.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Bane",
    hero_id: 60,
    intel: 88,
    strength: 38,
    speed: 23,
    durability: 56,
    power: 51,
    combat: 95,
    total_power: 351,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/637.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Hela",
    hero_id: 321,
    intel: 63,
    strength: 100,
    speed: 46,
    durability: 100,
    power: 100,
    combat: 45,
    total_power: 454,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/10835.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Evilhawk",
    hero_id: 248,
    intel: 50,
    strength: 32,
    speed: 33,
    durability: 70,
    power: 85,
    combat: 64,
    total_power: 334,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1516.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Dormammu",
    hero_id: 232,
    intel: 88,
    strength: 95,
    speed: 83,
    durability: 100,
    power: 100,
    combat: 80,
    total_power: 546,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1359.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Ego",
    hero_id: 235,
    intel: 88,
    strength: 80,
    speed: 83,
    durability: 99,
    power: 71,
    combat: 28,
    total_power: 449,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/6.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Moonstone",
    hero_id: 471,
    intel: 56,
    strength: 67,
    speed: 47,
    durability: 52,
    power: 74,
    combat: 80,
    total_power: 376,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/100.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Giganta",
    hero_id: 284,
    intel: 81,
    strength: 89,
    speed: 23,
    durability: 85,
    power: 32,
    combat: 42,
    total_power: 352,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1376.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Goblin Queen",
    hero_id: 286,
    intel: 75,
    strength: 10,
    speed: 23,
    durability: 28,
    power: 65,
    combat: 56,
    total_power: 546,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1054.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Godzilla",
    hero_id: 287,
    intel: 44,
    strength: 100,
    speed: 54,
    durability: 100,
    power: 100,
    combat: 20,
    total_power: 418,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/10590.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Gorilla Grodd",
    hero_id: 294,
    intel: 81,
    strength: 53,
    speed: 33,
    durability: 70,
    power: 100,
    combat: 65,
    total_power: 402,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/694.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Heat Wave",
    hero_id: 320,
    intel: 38,
    strength: 10,
    speed: 17,
    durability: 45,
    power: 27,
    combat: 30,
    total_power: 167,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/705.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Hydro-Man",
    hero_id: 337,
    intel: 38,
    strength: 13,
    speed: 25,
    durability: 80,
    power: 66,
    combat: 50,
    total_power: 272,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1451.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Joker",
    hero_id: 370,
    intel: 100,
    strength: 10,
    speed: 12,
    durability: 60,
    power: 43,
    combat: 70,
    total_power: 295,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/719.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "White Canary",
    hero_id: 711,
    intel: 63,
    strength: 7,
    speed: 33,
    durability: 15,
    power: 49,
    combat: 90,
    total_power: 257,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/10542.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Vulture",
    hero_id: 701,
    intel: 75,
    strength: 22,
    speed: 42,
    durability: 25,
    power: 26,
    combat: 30,
    total_power: 220,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1031.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Poison Ivy",
    hero_id: 522,
    intel: 81,
    strength: 14,
    speed: 21,
    durability: 40,
    power: 100,
    combat: 40,
    total_power: 296,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/757.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Pyro",
    hero_id: 532,
    intel: 38,
    strength: 10,
    speed: 12,
    durability: 14,
    power: 54,
    combat: 28,
    total_power: 156,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/853.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Sandman",
    hero_id: 572,
    intel: 44,
    strength: 75,
    speed: 46,
    durability: 90,
    power: 100,
    combat: 60,
    total_power: 415,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/621.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Scarecrow",
    hero_id: 576,
    intel: 81,
    strength: 10,
    speed: 12,
    durability: 14,
    power: 48,
    combat: 50,
    total_power: 215,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/819.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Sebastian Shaw",
    hero_id: 582,
    intel: 63,
    strength: 85,
    speed: 12,
    durability: 95,
    power: 36,
    combat: 56,
    total_power: 347,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1482.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Sentry",
    hero_id: 583,
    intel: 75,
    strength: 100,
    speed: 100,
    durability: 84,
    power: 100,
    combat: 40,
    total_power: 499,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/447.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Sinestro",
    hero_id: 601,
    intel: 75,
    strength: 85,
    speed: 53,
    durability: 64,
    power: 100,
    combat: 55,
    total_power: 432,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/781.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Steppenwolf",
    hero_id: 637,
    intel: 94,
    strength: 100,
    speed: 83,
    durability: 100,
    power: 100,
    combat: 100,
    total_power: 577,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/10653.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Swamp Thing",
    hero_id: 645,
    intel: 88,
    strength: 95,
    speed: 25,
    durability: 100,
    power: 100,
    combat: 55,
    total_power: 463,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/792.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Swarm",
    hero_id: 646,
    intel: 75,
    strength: 18,
    speed: 50,
    durability: 90,
    power: 38,
    combat: 35,
    total_power: 306,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/10428.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Taskmaster",
    hero_id: 653,
    intel: 75,
    strength: 12,
    speed: 50,
    durability: 20,
    power: 63,
    combat: 100,
    total_power: 320,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/21.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Tinkerer",
    hero_id: 668,
    intel: 100,
    strength: 10,
    speed: 23,
    durability: 14,
    power: 10,
    combat: 14,
    total_power: 171,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1036.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Utgard-Loki",
    hero_id: 681,
    intel: 50,
    strength: 80,
    speed: 23,
    durability: 81,
    power: 85,
    combat: 64,
    total_power: 386,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/1484.jpg",
    date: new Date(Date.now()),
  },
  {
    name: "Venom Pool",
    hero_id: 690,
    intel: 69,
    strength: 57,
    speed: 63,
    durability: 100,
    power: 100,
    combat: 100,
    total_power: 489,
    alignment: "bad",
    img_url: "https://www.superherodb.com/pictures2/portraits/10/100/10618.jpg",
    date: new Date(Date.now()),
  },
];

db.Villains.remove({})
  .then(() => db.Villains.collection.insertMany(villainSeed))
  .then((data) => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
